# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIView-AlertView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UIView-AlertView
  pod 'CustomIOSAlertView', '~> 0.9.5'
  target 'UIView-AlertViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
